# # version: '3.8'

services:
  frontend:
    container_name: reactServer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

# version: '3.8'

# services:
#   frontend:
#     container_name: react_production
#     build: .
#     ports:
#       - "80:80"  # Using standard HTTP port
#     restart: unless-stopped
#     environment:
#       - NODE_ENV=production